### ISSUE TITLE
Optional Default types instead of zero-initialized data?

### ISSUE THREAD

**Issue by ahorn** [devashishdxt/desse#3]
This is not a bug report in a traditional sense, but I was curious to find out more about desse.

I noticed that desse [currently uses `std::mem::zeroed()`](https://github.com/devashishdxt/desse/blob/f68470a7b91225a440647780653d2bc2a9f2f634/desse-derive/src/desse.rs#L35), which is being deprecated in favour for [`mem::MaybeUninit::zeroed`](https://doc.rust-lang.org/beta/std/mem/union.MaybeUninit.html). Would it make sense to (optionally) leverage the [`Default`](https://doc.rust-lang.org/std/default/trait.Default.html) trait if a type implements it? This would be safe code. Or does this cause too much performance overhead (if you happen to have run experiments along those lines)?

Thank you for your time!

**Comment by devashishdxt** [comment]
To be honest, I haven't benchmarked performance of [`std::mem::zeroed()`](https://doc.rust-lang.org/std/mem/fn.zeroed.html) vs [`Default::default()`](https://doc.rust-lang.org/std/default/trait.Default.html), but, I don't think there should be much difference there. The only reason I used `zeroed()` is because `Default` is not implemented for fixed size arrays of size above `32` (`[T; 32]`) and there are many cases where there are byte arrays of 64 bytes or even more than that (especially in cryptography and networking).

I think the need for using uninitialized values will go away once we have [`const_generics`](https://github.com/rust-lang/rfcs/blob/master/text/2000-const-generics.md).

What do you think?

**Comment by devashishdxt** [comment]
The use of `std::mem::zeroed()` was removed in https://github.com/devashishdxt/desse/commit/9d9026e67b041a609a89a9f24a8568506152b065 which changes deserialization strategy.

Closing this issue.

**Comment by ahorn** [comment]
Thank you for the changes and the links.
